build: false
skip_tags: true
cache:
- C:\Users\appveyor\.cargo\registry
- target
environment:
  global:
    CHANNEL: stable
    PROJECT_NAME: uom
    # APPVEYOR_CACHE_SKIP_RESTORE: true  # Uncomment when caching causes problems
  matrix:
  # Oldest supported
  # - TARGET: i686-pc-windows-msvc
  #   CHANNEL: 1.20.0
  # - TARGET: i686-pc-windows-gnu
  #   CHANNEL: 1.20.0
  # - TARGET: x86_64-pc-windows-msvc
  #   CHANNEL: 1.20.0
  # - TARGET: x86_64-pc-windows-gnu
  #   CHANNEL: 1.20.0
  # Stable channel
  - TARGET: i686-pc-windows-msvc
    CHANNEL: stable
  - TARGET: i686-pc-windows-gnu
    CHANNEL: stable
  - TARGET: x86_64-pc-windows-msvc
    CHANNEL: stable
  - TARGET: x86_64-pc-windows-gnu
    CHANNEL: stable
  # Beta channel
  # - TARGET: i686-pc-windows-msvc
  #   CHANNEL: beta
  # - TARGET: i686-pc-windows-gnu
  #   CHANNEL: beta
  # - TARGET: x86_64-pc-windows-msvc
  #   CHANNEL: beta
  # - TARGET: x86_64-pc-windows-gnu
  #   CHANNEL: beta
  # Nightly channel
  # - TARGET: i686-pc-windows-msvc
  #   CHANNEL: nightly
  # - TARGET: i686-pc-windows-gnu
  #   CHANNEL: nightly
  # - TARGET: x86_64-pc-windows-msvc
  #   CHANNEL: nightly
  # - TARGET: x86_64-pc-windows-gnu
  #   CHANNEL: nightly

matrix:
  allow_failures:
  - CHANNEL: nightly

install:
- appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
- rustup-init -yv --default-toolchain %CHANNEL% --default-host %TARGET%
- set PATH=%PATH%;%USERPROFILE%\.cargo\bin
- rustc -Vv
- cargo -V

test_script:
- cargo test --verbose --features "use_serde %CHANNEL:.=_%"

notifications:
- provider: Email
  on_build_success: false
