# Unstable and defective options commented out. Once stabilized or corrected these options will
# likely be enabled.

#comment_width = 100
#error_on_unformatted = true
#format_strings = true
#imports_indent = "Block"
#match_block_trailing_comma = true
newline_style = "Native"
#wrap_comments = true
#reorder_imports = true
