language: rust
cache:
  directories:
  - /home/travis/.cargo
sudo: false

rust:
- 1.31.0    # Oldest supported
- stable
- beta
- nightly
os:
- linux
- osx
- windows

matrix:
  allow_failures:
  - rust: nightly
  include:
  - name: "Rust: stable + tests"
    rust: stable
    script: |
      set -e
      # std
      cargo test --verbose --features "use_serde"
      # no_std
      cargo test --verbose --no-default-features --features "f32 f64 si use_serde"
      # All storage types, no SI.
      cargo test --verbose --no-run --no-default-features --features "usize u8 u16 u32 u64 u128 isize i8 i16 i32 i64 i128 bigint biguint rational rational32 rational64 bigrational f32 f64 std use_serde"
  - name: Rustfmt
    rust: stable
    install:
    - rustup component add rustfmt
    script:
    - cargo fmt -- --check
  - name: Deny warnings
    rust: stable
    script:
    - RUSTFLAGS="-D warnings" cargo check --tests
  - name: Clippy
    rust: stable
    install:
    - rustup component add clippy
    script:
    - cargo clippy -- -D clippy
  - name: Tarpaulin
    rust: stable
    sudo: required
    script:
    - docker run --security-opt seccomp=unconfined -v "$PWD:/volume" xd009642/tarpaulin sh -c "cargo build && cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID"
  exclude:
  - os: linux     # Done by explicit job.
    rust: stable

install:
- rustc -Vv
- cargo -V

script: |
  set -e
  cargo test --verbose --features "use_serde"

before_cache:
- rm -rf /home/travis/.cargo/registry

notifications:
  email:
    on_success: never
