language: rust
cache: cargo
sudo: false

# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

rust:
  - stable
  - beta
  - nightly
  - 1.20.0

matrix:
  allow_failures:
    - rust: nightly

before_script: |
  test "$TRAVIS_RUST_VERSION" != "stable" ||
  (test -x /home/travis/.cargo/bin/cargo-coveralls || cargo install cargo-travis) ||
  (test $(grep "cargo-travis" /home/travis/.cargo/.crates.toml | sed -r "s/\"cargo-travis ([^\ ]+).+/\1/") = $(cargo search cargo-travis --limit 1 | sed -r "s/cargo-travis \(([^\)]+)\).+/\1/") || cargoo install cargo-travis --force)

script: |
  cargo build --verbose --no-default-features --features "autoconvert usize u8 u16 u32 u64 isize i8 i16 i32 i64 bigint biguint rational rational32 rational64 bigrational f32 f64 si std use_serde" &&
  cargo test --verbose --no-run --no-default-features --features "autoconvert usize u8 u16 u32 u64 isize i8 i16 i32 i64 bigint biguint rational rational32 rational64 bigrational f32 f64 std use_serde $TRAVIS_RUST_VERSION" &&
  cargo test --verbose --features "use_serde $TRAVIS_RUST_VERSION" &&
  cargo test --manifest-path tests/feature_check/Cargo.toml --verbose --features "$TRAVIS_RUST_VERSION"

after_success: |
  test "$TRAVIS_RUST_VERSION" != "stable" || cargo coveralls

notifications:
  email:
    on_success: never
