[package]
name = "uom"
version = "0.15.0"
authors = ["Mike Boutin <mike.boutin@gmail.com>"]
description = "Units of measurement"
documentation = "https://docs.rs/uom"
#homepage = ""
repository = "https://github.com/iliekturtles/uom"
readme = "README.md"
keywords = ["units", "measurement", "SI", "dimensional-analysis", "no_std"]
categories = ["no-std", "science", "value-formatting"]
license = "Apache-2.0/MIT"

[badges]
appveyor = { repository = "iliekturtles/uom" }
travis-ci = { repository = "iliekturtles/uom" }
coveralls = { repository = "iliekturtles/uom" }

[dependencies]
num = "0.1"
typenum = "1.9.0"
clippy = { version = "^0", optional = true }
compiletest_rs = { version = "^0", optional = true }

[dev-dependencies]
quickcheck = "0.4.1"
approx = "0.1.1"

[features]
default = ["f32", "f64", "si", "std"]
usize = []
u8 = []
u16 = []
u32 = []
u64 = []
isize = []
i8 = []
i16 = []
i32 = []
i64 = []
bigint = []
biguint = []
rational = []
rational32 = []
rational64 = []
bigrational = []
f32 = []
f64 = []
si = []
std = []

[[example]]
name = "base"
required-features = ["f32", "si"]

[[example]]
name = "mks"
required-features = ["f32"]

[[example]]
name = "si"
required-features = ["f32", "si"]
