[package]
name = "uom"
version = "0.11.0"
authors = ["Mike Boutin <mike.boutin@gmail.com>"]
description = "Units of measurement"
documentation = "https://docs.rs/uom"
#homepage = ""
repository = "https://github.com/iliekturtles/uom"
readme = "README.md"
keywords = ["units", "measurement", "SI", "dimensional-analysis", "no_std"]
categories = ["science", "value-formatting"]
license = "Apache-2.0/MIT"

[dependencies]
typenum = "1.6.0"
clippy = {version = "0.0.114", optional = true}

[features]
default = ["f32", "f64", "si"]
f32 = []
f64 = []
si = []
