[package]
name = "uom"
version = "0.1.0"
authors = ["Mike Boutin <mike.boutin@gmail.com>"]
description = "Units of measurement"
#documentation = ""
#homepage = ""
repository = "https://github.com/iliekturtles/uom"
readme = "README.md"
keywords = ["uom", "units", "units of measurement", "SI", "International System of Units", "ISQ",
    "International System of Quantities", "dimensional analysis", "no_std"]
categories = ["science", "value-formatting"]
license = "Apache-2.0/MIT"

[dependencies]
clippy = {version = "*", optional = true}

[features]
default = []
std = []
